# WARNING - Generated by {fusen} from dev/flat_traitements_sim2.Rmd: do not edit by hand # nolint: line_length_linter.


test_that("def_periode works correctly with known dates (saison)", {
  # Jeu de données minimal contrôlé
  df <- data.frame(DATE = c(
    19601215, # décembre -> Hiver 1961
    19600110, # janvier -> Hiver 1960
    19600410, # avril -> Printemps 1960
    19600720, # juillet -> Ete 1960
    19601005  # octobre -> Automne 1960
  ))
  
  res <- def_periode(df, date_col = "DATE", periode = "saison")
  
  # Vérification des saisons
  expect_equal(res$periode,
               c("Hiver", "Hiver", "Printemps", "Ete", "Automne"))
  
  # Vérification des années
  expect_equal(res$annee, c(1961, 1960, 1960, 1960, 1960))
})

test_that("def_periode works correctly with known dates (annee)", {

  df <- data.frame(
    DATE = c(19601215, 19600110)
  )

  res <- def_periode(df, date_col = "DATE", periode = "annee")

  expect_true(all(res$periode == "Annee"))
  expect_equal(res$annee, c(1960, 1960))
})

library(testthat)
library(DBI)
library(duckdb)
library(dplyr)

test_that("def_periode works with tbl_lazy (DuckDB)", {

  # Connexion DuckDB en mémoire
  con <- dbConnect(duckdb::duckdb(), dbdir = ":memory:")

  # Créer un petit jeu de données
  df <- data.frame(
    DATE = c(19601215, 19600110, 19600410, 19600720, 19601005),
    T = c(1,2,3,4,5)
  )

  # Copier dans DuckDB
  dbWriteTable(con, "tbl_test", df)

  # Créer une table lazy
  tbl_lazy_test <- tbl(con, "tbl_test")

  # Appliquer la fonction
  res <- tbl_lazy_test %>%
    def_periode("DATE", "saison") %>%
    collect()

  # Vérifier les saisons
  expect_equal(res$periode, c("Hiver", "Hiver", "Printemps", "Ete", "Automne"))

  # Vérifier les années
  expect_equal(res$annee, c(1961, 1960, 1960, 1960, 1960))

  # Fermer la connexion
  dbDisconnect(con, shutdown = TRUE)
})

test_that("def_periode doesnt work", {

  # Jeu minimal valide
  df <- data.frame(
    DATE = c(19601215, 19600110),
    X = c(1, 2)
  )

  # Colonne inexistante
  expect_error(
    def_periode(df, date_col = "erreur", periode = "saison"),
    "non trouvée"
  )

  # Mauvais format AAAAMMJJ
  df_bad_format <- data.frame(
    DATE = c("1960-12-15", "1960-01-10")
  )

  expect_error(
    def_periode(df_bad_format, date_col = "DATE", periode = "saison"),
    "AAAAMMJJ"
  )

  # Mauvais paramètre periode
  expect_error(
    def_periode(df, date_col = "DATE", periode = "erreur"),
    "saison"
  )

  # Mauvais type de data
  expect_error(
    def_periode("ex_data_sim2", date_col = "DATE", periode = "saison"),
    "data.frame"
  )
})  
  
  
