# WARNING - Generated by {fusen} from dev/flat_traitements_sim2.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("def_periode works", {
  expect_true(inherits(def_periode, "function"))
})
