# WARNING - Generated by {fusen} from dev/flat_traitements_sim2.Rmd: do not edit by hand # nolint: line_length_linter.

library(testthat)
library(dplyr)
library(DBI)
library(duckdb)
library(arrow)

# -----------------------------
# Jeu de données de test
# -----------------------------
df_test <- tibble::tibble(
  annee = c(2020, 2020, 2021, 2021),
  periode = c("Hiver", "Hiver", "Ete", "Ete"),
  LAMBX = c(1, 1, 2, 2),
  LAMBY = c(3, 3, 4, 4),
  PRELIQ = c(10, 20, 30, 40)
)

# -----------------------------
# TESTS DATA.FRAME
# -----------------------------

test_that("calcul_periode works correctly with data.frame (mean)", {

  res <- calcul_periode(
    data = df_test,
    var = "PRELIQ",
    fun = "mean",
    group_vars = c("annee", "periode"),
    nom = "PRELIQ_moy"
  )

  expect_s3_class(res, "data.frame")
  expect_true("PRELIQ_moy" %in% colnames(res))
  
  expect_equal(res %>% filter(annee == 2020, periode == "Hiver") %>%
                 pull(PRELIQ_moy),
               15)
  expect_equal(res %>% filter(annee == 2021, periode == "Ete") %>%
                 pull(PRELIQ_moy),
               35)
})

test_that("calcul_periode works correctly with data.frame (sum)", {

  res <- calcul_periode(
    data = df_test,
    var = "PRELIQ",
    fun = "sum",
    group_vars = c("annee", "periode"),
    nom = "PRELIQ_sum"
  )
  
  expect_equal(res %>% filter(annee == 2020, periode == "Hiver") %>%
                 pull(PRELIQ_sum),
               30)
  expect_equal(res %>% filter(annee == 2021, periode == "Ete") %>%
                 pull(PRELIQ_sum),
               70)
})

# -----------------------------
# TESTS TBL_LAZY (DuckDB)
# -----------------------------

test_that("calcul_periode works correctly with tbl_lazy", {

  con <- dbConnect(duckdb())
  on.exit(dbDisconnect(con, shutdown = TRUE))

  tbl_lazy_test <- copy_to(con, df_test, temporary = TRUE)

  res <- calcul_periode(
    data = tbl_lazy_test,
    var = "PRELIQ",
    fun = "sum",
    group_vars = c("annee", "periode"),
    nom = "PRELIQ_sum"
  ) %>%
    collect()

  expect_s3_class(res, "data.frame")
  expect_equal(res %>% filter(annee == 2020, periode == "Hiver") %>%
                 pull(PRELIQ_sum),
               30)
  expect_equal(res %>% filter(annee == 2021, periode == "Ete") %>%
                 pull(PRELIQ_sum),
               70)
})


# -----------------------------
# TESTS ARROW
# -----------------------------

test_that("calcul_periode works correctly with  Arrow Dataset", {
  
  # dossier temporaire
  tmp_dir <- tempfile()
  dir.create(tmp_dir)

  # écrire un fichier parquet
  arrow::write_dataset(df_test, path = tmp_dir, format = "parquet")

  # ouvrir dataset
  ds <- arrow::open_dataset(tmp_dir)

  res <- calcul_periode(
    data = ds,
    var = "PRELIQ",
    fun = "sum",
    group_vars = c("annee", "periode"),
    nom = "PRELIQ_sum"
  ) %>%
    collect()

  expect_s3_class(res, "data.frame")

  expect_equal(
    res %>% filter(annee == 2020, periode == "Hiver") %>%
      pull(PRELIQ_sum),
    30)

  expect_equal(
    res %>% filter(annee == 2021, periode == "Ete") %>%
      pull(PRELIQ_sum),
    70)
  
})

# -----------------------------
# TESTS ERREURS INPUT
# -----------------------------

test_that("calcul_periode errors correctly", {
  
  expect_error(
    calcul_periode(
      data = df_test,
      var = "PRELIQ",
    fun = "median",
    group_vars = c("annee", "periode"),
    nom = "PRELIQ_moy"),
    "`fun_name` doit etre 'mean','sum','min' ou 'max'"
  )
})


