# WARNING - Generated by {fusen} from dev/flat_traitements_sim2.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("def_periode works correctly with data.frame (saison)", {

  df <- data.frame(DATE = c(
    19601215, # décembre -> Hiver 1961
    19600110, # janvier -> Hiver 1960
    19600410, # avril -> Printemps 1960
    19600720, # juillet -> Ete 1960
    19601005  # octobre -> Automne 1960
  ))

  res <- def_periode(df, date_col = "DATE", periode = "saison")

  expect_equal(
    res$periode,
    c("Hiver", "Hiver", "Printemps", "Ete", "Automne")
  )

  expect_equal(
    res$annee,
    c(1961, 1960, 1960, 1960, 1960)
  )
})

test_that("def_periode works correctly with data.frame (annee)", {

  df <- data.frame(DATE = c(19601215, 19600110))

  res <- def_periode(df, date_col = "DATE", periode = "annee")

  expect_true(all(res$periode == "Annee"))
  expect_equal(res$annee, c(1960, 1960))
})

test_that("def_periode works with DuckDB tbl_lazy", {

  skip_if_not_installed("duckdb")
  skip_if_not_installed("DBI")

  library(DBI)
  library(dplyr)

  con <- dbConnect(duckdb::duckdb(), dbdir = ":memory:")

  df <- data.frame(
    DATE = c(19601215, 19600110, 19600410, 19600720, 19601005),
    T = 1:5
  )

  dbWriteTable(con, "tbl_test", df)

  tbl_lazy_test <- tbl(con, "tbl_test")

  res <- tbl_lazy_test %>%
    def_periode("DATE", "saison") %>%
    collect()

  expect_equal(
    res$periode,
    c("Hiver", "Hiver", "Printemps", "Ete", "Automne")
  )

  expect_equal(
    res$annee,
    c(1961, 1960, 1960, 1960, 1960)
  )

  dbDisconnect(con, shutdown = TRUE)
})

test_that("def_periode works with Arrow Dataset", {

  skip_if_not_installed("arrow")

  library(arrow)
  library(dplyr)

  df <- data.frame(
    DATE = c(19601215, 19600110, 19600410, 19600720, 19601005),
    T = 1:5
  )

  tmp_dir <- tempfile()
  dir.create(tmp_dir)

  write_dataset(df, tmp_dir, format = "parquet")

  ds <- open_dataset(tmp_dir)

  res <- ds %>%
    def_periode("DATE", "saison") %>%
    collect()

  expect_equal(
    res$periode,
    c("Hiver", "Hiver", "Printemps", "Ete", "Automne")
  )

  expect_equal(
    res$annee,
    c(1961, 1960, 1960, 1960, 1960)
  )
})

test_that("def_periode errors correctly", {

  df <- data.frame(DATE = c(19601215, 19600110))

  # Colonne inexistante
  expect_error(
    def_periode(df, date_col = "BAD", periode = "saison"),
    "Colonne 'BAD' non trouvee."
  )

  # Mauvais paramètre periode
  expect_error(
    def_periode(df, date_col = "DATE", periode = "erreur"),
    "`periode` doit etre 'saison' ou 'annee'"
  )

  # Mauvais type d'objet
  expect_error(
    def_periode("not_a_table", date_col = "DATE", periode = "saison"),
    "`data` doit etre un data.frame, un tbl_lazy ou un Dataset Arrow."
  )
})

