# WARNING - Generated by {fusen} from dev/flat_traitements_sim2.Rmd: do not edit by hand # nolint: line_length_linter.

library(testthat)
library(dplyr)

df_test <- tibble::tibble(
  LAMBX = c(1,1,2,2),
  LAMBY = c(3,3,4,4),
  periode = c("Hiver","Hiver","Ete","Ete"),
  annee = c(2000,2001,2000,2001),
  T_moy = c(10, 11, 20, 21)
)

test_that("regression_lineaire works correctly", {
  res <- regression_lineaire(df_test, var = "T_moy", group_vars = c("LAMBX","LAMBY","periode"))
  
  # Classe du retour
  expect_s3_class(res, "data.frame")
  
  # Colonnes présentes
  expect_true(all(c("LAMBX","LAMBY","periode","slope","p_value") %in% colnames(res)))
  
  # Vérifier les valeurs de pente
  expect_equal(res$slope, c(1, 1))  # ici 2 groupes : Hiver et Ete
  
})

test_that("regression_lineaire errors correctly", {
  
  # Erreur var
  expect_error(regression_lineaire(df_test, var = "Tmax", group_vars = c("LAMBX","LAMBY","periode")))
  
  # Erreur group_vars
  expect_error(regression_lineaire(df_test, var = "T_moy", group_vars = c("LAMBX","foo")))
  
})
