# WARNING - Generated by {fusen} from dev/flat_traitements_sim2.Rmd: do not edit by hand # nolint: line_length_linter.

library(testthat)
library(dplyr)
library(arrow)
library(duckdb)

# -----------------------------
# Jeu de données de test
# -----------------------------
df_test <- tibble::tibble(
  annee = c(2020, 2020, 2021, 2021),
  periode = c("Hiver", "Hiver", "Ete", "Ete"),
  LAMBX = c(1, 1, 2, 2),
  LAMBY = c(3, 3, 4, 4),
  PRELIQ = c(10, 20, 30, 40),
  T = c(5, 7, 6, 8)
)

vars_funs <- list(
  T = list(fun = "mean", nom = "T_moy"),
  PRELIQ = list(fun = "sum", nom = "PRELIQ_sum")
)

# -----------------------------
# TESTS DATA.FRAME
# -----------------------------
test_that("calcul_periode_multi works with data.frame", {
  
  res_list <- calcul_periode_multi(
    data = df_test,
    vars_funs = vars_funs,
    year_filter = c(2020, 2021),
    group_vars = c("LAMBX","LAMBY","annee","periode")
  )
  
  expect_true(is.list(res_list))
  expect_named(res_list, c("T_moy","PRELIQ_sum"))
  
  # Vérification contenu
  expect_equal(
    res_list$PRELIQ_sum %>% filter(annee == 2020, periode == "Hiver") %>% pull(PRELIQ_sum),
    30
  )
  
  expect_equal(
    res_list$T_moy %>% filter(annee == 2021, periode == "Ete") %>% pull(T_moy),
    7
  )
  
})

# -----------------------------
# TESTS ARROW
# -----------------------------
test_that("calcul_periode_multi works with Arrow Dataset", {
  
  tmp_dir <- tempfile()
  dir.create(tmp_dir)
  arrow::write_dataset(df_test, path = tmp_dir, format = "parquet")
  ds <- arrow::open_dataset(tmp_dir)
  
  res_list <- calcul_periode_multi(
    data = ds,
    vars_funs = vars_funs,
    year_filter = c(2020, 2021),
    group_vars = c("LAMBX","LAMBY","annee","periode")
  )
  
  expect_true(is.list(res_list))
  expect_named(res_list, c("T_moy","PRELIQ_sum"))
  
  expect_equal(
    res_list$PRELIQ_sum %>% filter(annee == 2020, periode == "Hiver") %>% pull(PRELIQ_sum),
    30
  )
})

# -----------------------------
# TESTS INPUT ERRORS
# -----------------------------
test_that("calcul_periode_multi errors correctly", {
  
  expect_error(
    calcul_periode_multi(
      data = df_test,
      vars_funs = vars_funs,
      year_filter = c(2021, 2020), # premier > second
      group_vars = c("LAMBX","LAMBY","annee","periode")
    ),
    "`year_filter` doit etre un vecteur numerique de longueur 2 avec le premier element < second"
  )
  
  expect_error(
    calcul_periode_multi(
      data = df_test,
      vars_funs = vars_funs,
      year_filter = "2020-2021", # pas numeric
      group_vars = c("LAMBX","LAMBY","annee","periode")
    ),
    "`year_filter` doit etre un vecteur numerique de longueur 2 avec le premier element < second"
  )
  
})
