# WARNING - Generated by {fusen} from dev/integration_sim2.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("concatenation_sim2 works", {
  expect_true(inherits(concatenation_sim2, "function")) 
})
