# WARNING - Generated by {fusen} from dev/flat_traitements_sim2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Calculer une statistique par période sur plusieurs cas
#'
#' Cette fonction applique `calcul_periode()` sur plusieurs colonnes et fonctions spécifiées dans `vars_funs`. Elle retourne une liste de tables, chacune correspondant à une combinaison variable / fonction. Elle permet également de filtrer les données sur des années avec `year_filter`.
#'
#' @param data data.frame, tibble, `arrow::Dataset` ou `tbl_lazy`. Table contenant les données.
#' @param vars_funs liste nommée, chaque élément correspond à une variable à agréger et doit contenir :
#'   \describe{
#'     \item{fun}{Caractère. Fonction d’agrégation à appliquer (`"mean"`, `"sum"`, `"min"`, `"max"`).}
#'     \item{nom}{Caractère. Nom de la colonne résultat dans la table finale.}
#'   }
#'   Exemple : \code{list(T = list(fun = "mean", nom = "T_moy"),
#'                        PRELIQ = list(fun = "sum", nom = "PRELIQ_sum"))}
#' @param group_vars Character vector. Noms des colonnes servant à regrouper les données (par défaut `c("LAMBX", "LAMBY", "annee", "periode")`).
#' @param year_filter Numeric vector de longueur 2. Années minimales et maximales pour filtrer les données (par défaut `c(1959, 2025)`).
#'
#' @importFrom purrr map_chr map2 map
#' @importFrom dplyr filter collect
#' 
#' @return Liste de tibbles. Chaque élément correspond à une table calculée pour une variable/fonction, avec les colonnes de regroupement et la colonne résultat renommée selon `nom`.
#' 
#' @export
#'
#' @examples
#'
#'
#' ######################################################
#' # Exemple avec un data.table
#'
#' data("ex_data_sim2")
#'
#' data = def_periode(
#'   data = ex_data_sim2,
#'   date_col = "DATE",
#'   periode = "annee"
#' )
#'
#' vars_funs <- list(
#'   T = list(fun = "mean", nom = "T_moy"),
#'   PRELIQ = list(fun = "sum", nom = "PRELIQ_sum")
#' )
#'
#' result_list <- calcul_periode_multi(data, vars_funs)
#'
#' head(result_list)
#'
#' ######################################################
#' # Exemple avec un fichier Parquet / Arrow
#'
#' if (requireNamespace("arrow", quietly = TRUE)) {
#'   
#'   # Chemin vers le parquet dans le package
#'   file <- system.file("ex_data_sim2.parquet", package = "franceclimat")
#'   
#'   # Ouvrir le dataset
#'   ds <- arrow::open_dataset(file)
#'   
#'   vars_funs <- list(
#'     TSUP_H = list(fun = "mean", nom = "Tmax_moy"),
#'     PRENEI = list(fun = "max", nom = "PRENEI_max")
#'   )
#'   
#'   # Ajouter les périodes
#'   ds <- def_periode(ds, date_col = "DATE", periode = "saison")
#'   
#'   # Appliquer calcul_periode_multi sur le dataset Arrow
#'   resultat_arrow <- calcul_periode_multi(
#'     data = ds,
#'     vars_funs = vars_funs,
#'     year_filter = c(1959, 2025),
#'     group_vars = c("LAMBX", "LAMBY", "annee", "periode")
#'   )
#'   
#'   head(resultat_arrow)
#'
#' }
#'
#'
calcul_periode_multi <- function(data,
                                 vars_funs,   
                                 year_filter = c(1959, 2025),
                                 group_vars = c("LAMBX", "LAMBY", "annee", "periode")
                                 ) {
  
  # Vérification year_filter
  assert_that(is.numeric(year_filter), 
              length(year_filter) == 2, 
              year_filter[1] < year_filter[2],
              msg = "`year_filter` doit etre un vecteur numerique de longueur 2 avec le premier element < second")
  
  # Extraire les noms et fonctions dans des vecteurs
  varnames <- names(vars_funs)
  noms_col <- map_chr(vars_funs, "nom")
  funs <- map(vars_funs, "fun")
  
  year_col <- "annee"  # le nom de la colonne pour filter

  # map2 pour itérer sur les fonctions et les colonnes
  result_list <- map2(varnames, funs, ~ {
    calcul_periode(
      data = data,
      var = .x,
      fun = .y,
      group_vars = c("LAMBX","LAMBY","annee","periode"),
      nom = noms_col[which(varnames == .x)]
    ) %>%
      collect() %>%
      filter(.[[year_col]] >= year_filter[1], .[[year_col]] <= year_filter[2])
  })
  
  names(result_list) <- noms_col
  
  return(result_list)

}
