# WARNING - Generated by {fusen} from dev/flat_traitements_sim2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Calculer une statistique par période
#'
#' Cette fonction regroupe les données selon les variables spécifiées dans `group_vars` et applique une fonction d’agrégation sur une colonne donnée.
#' Compatible avec `data.frame` / `tibble`, `arrow::Dataset` et `duckdb` (`tbl_lazy`)
#' Pour garantir la compatibilité avec Arrow et DuckDB, la fonction d’agrégation est fournie sous forme de chaîne de caractères (`fun_name`) et doit correspondre à une fonction d’agrégation standard supportée par ces moteurs.
#'
#' @param data data.frame, tibble, `arrow::Dataset` ou `tbl_lazy`. Table contenant les données à agréger.
#' @param var Character. Nom de la colonne numérique sur laquelle appliquer la fonction d’agrégation.
#' @param group_vars Character vector. Noms des colonnes servant à regrouper les données (par exemple `c("annee", "periode")`).
#' @param fun_name Character. Nom de la fonction d’agrégation à appliquer. Doit être l’une des valeurs suivantes : `"mean"`, `"sum"`, `"min"`, `"max"`.
#' @param nom Character. Nom de la colonne résultat créée après agrégation.
#' 
#' @importFrom dplyr group_by summarise across rename all_of
#'
#' @return tibble avec les colonnes de regroupement et la colonne agrégée `nom`.
#' 
#' @export
#'
#' @examples
#'
#'
#' library(dplyr)
#'
#' ######################################################
#' # Exemple avec un data.table
#'
#' data("ex_data_sim2")
#'
#' resultat = ex_data_sim2 %>%
#'   def_periode(date_col = "DATE",
#'               periode = "saison") %>%
#'   calcul_periode(var = "T",
#'                  fun_name = "mean",
#'                  group_vars = c("LAMBX", "LAMBY", "annee", "periode"),
#'                  nom = "T_moy")
#'
#' head(resultat)
#'
#' ######################################################
#' # Exemple avec un parquet / tbl_lazy
#'
#'
#' if (requireNamespace("duckdb", quietly = TRUE)) {
#'   
#'   library(DBI)
#'   
#'   # Chemin vers le parquet dans le package
#'   file <- system.file("ex_data_sim2.parquet", package = "franceclimat")
#'   
#'   # Connexion DuckDB en mémoire
#'   con <- dbConnect(duckdb::duckdb())
#'   
#'   # Création d'une table lazy directement depuis le parquet
#'   tbl_lazy <- tbl(con, sql(sprintf("SELECT * FROM read_parquet('%s')", file)))
#'   
#'   resultat_tbl_lazy <- tbl_lazy %>%
#'     def_periode(date_col = "DATE", periode = "saison") %>%
#'     calcul_periode(
#'       var = "PRELIQ",
#'       fun_name = "sum",
#'       group_vars = c("LAMBX", "LAMBY", "annee", "periode"),
#'       nom = "PRELIQ_sum"
#'     ) %>%
#'     collect()
#'   
#'   dbDisconnect(con, shutdown = TRUE)
#'   
#'   head(resultat_tbl_lazy)
#'   
#' }
#'
#' # ######################################################
#' # Exemple avec un fichier Parquet / Arrow
#'
#' if (requireNamespace("arrow", quietly = TRUE)) {
#'
#'   library(arrow)
#'
#'   # Chemin vers le parquet dans le package
#'   file <- system.file("ex_data_sim2.parquet", package = "franceclimat")
#'
#'   # Ouvrir le dataset
#'   ds <- arrow::open_dataset(file)
#'
#'   # Ajouter les périodes (saison) puis collecter le résultat
#'   resultat_arrow <- ds %>%
#'     def_periode(date_col = "DATE", periode = "saison") %>%
#'     calcul_periode(
#'       var = "TSUP_H",
#'       fun = "mean",
#'       group_vars = c("LAMBX", "LAMBY", "annee", "periode"),
#'       nom = "TSUP_H_moy"
#'     ) %>%
#'     collect()
#'
#'   head(resultat_arrow)
#'
#' }
#'
calcul_periode <- function(data,
                           var = "col_calcul",
                           group_vars = c("annee","periode"),
                           fun_name = c("mean","sum","min","max"),
                           nom = "col_resultat") {
  
  # Vérifications
  if (!fun_name %in% c("mean","sum","min","max")) {
    stop("`fun_name` doit etre 'mean','sum','min' ou 'max'",
         call. = FALSE)
  }
  
  if (!is.character(nom) || length(nom) != 1) stop("`nom` doit etre un string de longueur 1.")
  if (!is.character(var) || length(var) != 1) stop("`var` doit etre un string correspondant au nom d'une colonne.")
  if (!is.character(group_vars)) stop("`group_vars` doit etre un vecteur de noms de colonnes (strings).")
  
  # Création colonne valeur qui est celle qu'on souhaite agréger
  # Pas fait de façon dynamique car non transposable avec arrow et duckbd
  
  data <- data %>%
    rename(col_calcul = var)
  
  # Calculs avec la fonction choisie
  # A nouveau, pas fait de façon dynamique car non transposable avec arrow et duckbd

  if (fun_name == "mean") {
    result <- data %>%
      group_by(across(all_of(group_vars))) %>%
      summarise(valeur = mean(col_calcul, na.rm = TRUE), .groups = "drop")

  } else if (fun_name == "sum") {
    result <- data %>%
      group_by(across(all_of(group_vars))) %>%
      summarise(valeur = sum(col_calcul, na.rm = TRUE), .groups = "drop")

  } else if (fun_name == "min") {
    result <- data %>%
      group_by(across(all_of(group_vars))) %>%
      summarise(valeur = min(col_calcul, na.rm = TRUE), .groups = "drop")

  } else if (fun_name == "max") {
    result <- data %>%
      group_by(across(all_of(group_vars))) %>%
      summarise(valeur = max(col_calcul, na.rm = TRUE), .groups = "drop")
  }

  # On renome la colonne valeur avec le nom indiqué en paramètre
  result = result %>%
    rename(!!nom := valeur)

  return(result)
}
