# WARNING - Generated by {fusen} from dev/integration_sim2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Fusionne des fichiers CSV.gz en un seul fichier via DuckDB
#'
#' Cette fonction lit tous les fichiers compressés au format `.csv.gz`
#' présents dans un dossier, les concatène, puis écrit le résultat
#' dans un fichier de sortie (CSV ou Parquet). La lecture et l'écriture se font en streaming via DuckDB,
#' ce qui permet de traiter de très gros volumes de données
#' (plusieurs dizaines de Go) sans saturer la mémoire RAM.
#'
#' @param input_dir Character. Chemin vers le dossier contenant les fichiers `.csv.gz`.
#' @param output_file Character. Chemin complet vers le fichier de sortie.
#' @param delim Character. Séparateur des fichiers CSV. Par défaut `";"`.
#' @param format Character. Format de sortie : `"parquet"` (par défaut) ou `"csv"`.
#'
#' @importFrom assertthat assert_that
#' @importFrom DBI dbConnect dbExecute dbDisconnect
#' @importFrom duckdb duckdb
#'
#' @return Character. Chemin du fichier généré (retourné invisiblement).
#' @export
#'
#' @examples
#' \dontrun{
#' concatenation_sim2(
#'   input_dir = "C:/workspace/sim/",
#'   output_file = "C:/workspace/sim/ALL_sim2.parquet",
#'   delim = ";",
#'   format = "parquet"
#' )
#' }
#'
concatenation_sim2 <- function(input_dir,
                               output_file,
                               delim = ";",
                               format = c("parquet", "csv")) {
  
  format <- match.arg(format)
  
  # Vérifications
  assert_that(dir.exists(input_dir),
              msg = "Le dossier d\u0027entr\u00E9e n\u0027existe pas.") # \u00E9 -> é / \u0027 -> '
  
  gz_files <- list.files(input_dir,
                         pattern = "\\.csv\\.gz$",
                         full.names = TRUE)
  
  assert_that(length(gz_files) > 0,
              msg = "Aucun fichier .csv.gz trouv\u00E9e dans le dossier.")
  
  assert_that(is.character(output_file),
              msg = "output_file doit \u00EAtre un chemin valide.") # \u00EA -> ê
  
  # Connexion DuckDB (temporaire en mémoire)
  con <- dbConnect(duckdb())
  on.exit(dbDisconnect(con, shutdown = TRUE), add = TRUE)
  
  # Normalisation des chemins (important sous Windows)
  input_dir_norm <- normalizePath(input_dir, winslash = "/")
  output_file_norm <- normalizePath(output_file,
                                    winslash = "/",
                                    mustWork = FALSE)
  
  message("Ex\u00E9ecution de la fusion via DuckDB...")
  
  if (format == "csv") {
    
    query <- sprintf(
      "COPY (
         SELECT *
         FROM read_csv('%s/*.csv.gz', delim='%s', header=true)
       )
       TO '%s'
       WITH (HEADER, DELIMITER '%s')",
      input_dir_norm, delim,
      output_file_norm, delim
    )
    
  } else {
    
    query <- sprintf(
      "COPY (
         SELECT *
         FROM read_csv('%s/*.csv.gz', delim='%s', header=true)
       )
       TO '%s'
       (FORMAT PARQUET)",
      input_dir_norm, delim,
      output_file_norm
    )
    
  }
  
  dbExecute(con, query)
  
  message("Fichier cr\u00E9e\u00E9e : ", output_file)
  
  invisible(output_file)
}

