# WARNING - Generated by {fusen} from dev/flat_traitements_sim2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Définir une période temporelle (année ou saison)
#'
#' À partir d'une table contenant une colonne de dates au format AAAAMMJJ (année-mois-jour),
#' cette fonction ajoute deux colonnes :
#' \itemize{
#'   \item `periode` : période temporelle ("Hiver", "Printemps", "Ete", "Automne" ou "Annee")
#'   \item `annee` : année associée à la période
#' }
#'
#' Lorsque `periode = "saison"`, les saisons météorologiques sont définies comme suit :
#' \itemize{
#'   \item Hiver : décembre à février
#'   \item Printemps : mars à mai
#'   \item Été : juin à août
#'   \item Automne : septembre à novembre
#' }
#'
#' L'année associée à l'hiver correspond à l'année de janvier/février.  Ainsi, décembre 1960 est rattaché à l'hiver 1961.
#'
#' @param data data.frame, tbl_lazy (DuckDB) ou Dataset (Dataset Arrow). Table contenant les données.
#' @param date_col Character. Nom de la colonne représentant la date (format AAAAMMJJ).
#' @param periode Character. Soit `"saison"` pour créer les saisons, soit `"annee"` pour créer simplement l'année.
#' 
#' @importFrom dplyr mutate case_when select
#'
#' @return Même objet que `data` avec deux colonnes supplémentaires :
#' \describe{
#'   \item{periode}{Période temporelle (Hiver, Printemps, Ete, Automne ou Annee)}
#'   \item{annee}{Année associée à la période}
#' }
#'
#' @export
#'
#' @examples
#'
#'
#' library(dplyr)
#'
#' ######################################################
#' # Exemple avec data.frame
#'
#' data("ex_data_sim2")
#'
#' resultat_df <- def_periode(
#'   data = ex_data_sim2,
#'   date_col = "DATE",
#'   periode = "saison"
#' )
#'
#' ######################################################
#' # Exemple avec DuckDB / parquet
#'
#' if (requireNamespace("duckdb", quietly = TRUE)) {
#'
#'   library(DBI)
#'   
#'   file <- system.file("ex_data_sim2.parquet", package = "franceclimat")
#'
#'   con <- DBI::dbConnect(duckdb::duckdb())
#'
#'   tbl_lazy <- dplyr::tbl(
#'     con,
#'     dbplyr::sql(sprintf("SELECT * FROM read_parquet('%s')", file))
#'   )
#'
#'   resultat_tbl_lazy <- tbl_lazy %>%
#'     def_periode("DATE", "saison") %>%
#'     collect()
#'
#'   DBI::dbDisconnect(con, shutdown = TRUE)
#' }
#'
#' ######################################################
#' # Exemple avec Arrow
#'
#' if (requireNamespace("arrow", quietly = TRUE)) {
#'
#'   library(arrow)
#'   
#'   
#'   file <- system.file("ex_data_sim2.parquet", package = "franceclimat")
#'
#'   ds <- arrow::open_dataset(file)
#'
#'   resultat_arrow <- ds %>%
#'     def_periode("DATE", "saison") %>%
#'     collect()
#' }
#'
def_periode <- function(data, date_col = "DATE", periode = "saison") {
  
  # -----------------------------
  # Vérifications
  # -----------------------------

  if (!periode %in% c("saison", "annee")) {
    stop("`periode` doit etre 'saison' ou 'annee'.", call. = FALSE)
  }
  
  
  if (!inherits(data, c("data.frame", "tbl_lazy", "Dataset"))) {
    stop("`data` doit etre un data.frame, un tbl_lazy ou un Dataset Arrow.",
         call. = FALSE)
  }
  
  if (!date_col %in% colnames(data)) {
    stop("Colonne '", date_col, "' non trouvee.", call. = FALSE)
  }
  
  # Vérification format UNIQUEMENT si data.frame
  if (inherits(data, "data.frame")) {
    if (!is.character(data[[date_col]]) &&
        !is.numeric(data[[date_col]])) {
      stop("`date_col` doit etre caractere ou numerique AAAAMMJJ.",
           call. = FALSE)
    }
  }
  
  # -----------------------------
  # Traitements
  # -----------------------------
  
  data <- data %>%
    dplyr::mutate(
      .date_chr = as.character(.data[[date_col]]),
      .year  = as.integer(substr(.date_chr, 1, 4)),
      .month = as.integer(substr(.date_chr, 5, 6))
    )

  if (periode == "saison") {

    data <- data %>%
      dplyr::mutate(
        periode = dplyr::case_when(
          .month %in% c(12, 1, 2) ~ "Hiver",
          .month %in% 3:5         ~ "Printemps",
          .month %in% 6:8         ~ "Ete",
          .month %in% 9:11        ~ "Automne"
        ),
        annee = dplyr::case_when(
          .month == 12 ~ .year + 1L,
          TRUE ~ .year
        )
      )

  } else {

    data <- data %>%
      dplyr::mutate(
        periode = "Annee",
        annee = .year
      )
  }

  result = data %>%
    dplyr::select(-.date_chr, -.year, -.month)
  
  return(result)
}

