# WARNING - Generated by {fusen} from dev/flat_traitements_sim2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Effectuer une régression linéaire par groupe
#'
#' Cette fonction effectue une régression linéaire du type `var ~ annee` pour chaque combinaison des colonnes spécifiées dans `group_vars`. Elle retourne la pente (estimate) et la valeur-p associée à la variable temporelle `annee`.
#'
#' @param data Un `data.frame` ou `tibble` contenant les colonnes à analyser.
#' @param var Character. Nom de la colonne numérique à utiliser comme variable dépendante dans la régression.
#' @param group_vars Character vector. Noms des colonnes servant à grouper les données avant la régression.
#' 
#' @importFrom dplyr group_by nest mutate select ungroup all_of
#' @importFrom tidyr unnest nest 
#' @importFrom purrr map
#' @importFrom broom tidy
#'
#' @return Un tibble avec les colonnes de regroupement, la pente (`slope`) et la valeur-p (`p_value`) pour chaque groupe.
#'
#' @export
#'
#' @examples
#'
#'
#' data("ex_data_sim2")
#'
#' data = ex_data_sim2 %>%
#'   def_periode(date_col = "DATE",
#'               periode = "saison") %>%
#'   calcul_periode(var = "T",
#'                  fun_name = "mean",
#'                  group_vars = c("LAMBX", "LAMBY", "annee", "periode"),
#'                  nom = "T_moy")
#'
#' res_lm <- regression_lineaire(
#'   data = data,
#'   var = "T_moy",
#'   group_vars = c("LAMBX", "LAMBY", "periode")
#' )
#'
#'
regression_lineaire <- function(data,
                                var = "col_calcul",
                                group_vars = c("LAMBX", "LAMBY", "periode")) {
  
  # Vérifications simples
  assert_that(is.data.frame(data) || inherits(data, "tbl"), 
              msg = "`data` doit etre un data.frame ou tibble")
  assert_that(is.character(var) && length(var) == 1, 
              msg = "`var` doit etre un string d'une seule colonne")
  assert_that(var %in% colnames(data), 
              msg = paste("La colonne", var, "n'existe pas dans data"))
  assert_that(all(group_vars %in% colnames(data)),
              msg = "Certaines colonnes de group_vars n'existent pas dans data")
  assert_that("annee" %in% colnames(data),
              msg = "La colonne 'annee' doit exister dans data pour la regression")
  
  # Regression
  res_lm <- data %>%
    group_by(across(all_of(group_vars))) %>% # Grouper les données selon les colonnes spécifiées dans group_vars
    nest() %>% # Créer une liste de tibbles par groupe pour pouvoir appliquer le modèle à chaque sous-ensemble
    # Appliquer la régression linéaire à chaque tibble (par point et période)
    mutate(
      model = map(data, ~ lm(.x[[var]] ~ annee, data = .x)),  # modèle lm(y = var, x = annee)
      tidy  = map(model, broom::tidy)                         # transformer le modèle en tibble avec estimate, p.value...
      ) %>%
    select(-data, -model) %>%
    unnest(tidy) %>% # Déplier les tibbles stockés dans 'tidy' pour avoir une table plate
    filter(term == "annee") %>% # Garder uniquement la pente associée à 'annee' (on ne veut pas l'intercept)
    select(all_of(group_vars),       # colonnes de regroupement (LAMBX, LAMBY, periode, ...)
           slope = estimate,         # la pente du modèle
           p_value = p.value          # la valeur p associée à la pente
           )

  return(res_lm)
  
}
